# .github/workflows/release.yaml

on:
  push: # 每次 push 的时候触发

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') # 只有这次 Commit 是 创建 Tag 时，才进行后续发布操作
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master # checkout 代码
      - uses: actions/setup-go@v2 # 配置 Go 环境
        with:
          go-version: "1.19.1" # 改成自己的版本

      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o chat2code_linux_amd64 ./cmd/chat2code
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o chat2code_windows_amd64.exe ./cmd/chat2code
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o chat2code_darwin_amd64 ./cmd/chat2code
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o chat2code_linux_arm64 ./cmd/chat2code
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -o chat2code_windows_arm64.exe ./cmd/chat2code
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o chat2code_darwin_arm64 ./cmd/chat2code

      - name: Release
        uses: softprops/action-gh-release@v1
        with: # 将下述可执行文件 release 上去
          files: |
            chat2code_linux_amd64
            chat2code_windows_amd64.exe
            chat2code_darwin_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}